name=SimpleESPNow
version=0.0.0
author=Henning Schreiber
maintainer=Henning Schreiber
sentence=A library 
paragraph=Nö
category=Communication
url=http://example.com/
architectures=espressif32
includes=SimpleESPNow.http
depends=